version: "3.9"

services:
  backend:
    build: ./backend  # Build the backend image from the Dockerfile in ./backend directory
    ports:
      - "4000:4000"  # Expose backend on port 4000
    networks:
      - mern
    environment:
      MONGO_URI: mongodb://mongodb:27017
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    build: ./frontend  # Build the frontend image from the Dockerfile in ./frontend directory
    ports:
      - "5173:5173"  # Expose frontend on port 5173
    networks:
      - mern
    environment:
      REACT_APP_API_URL: http://backend:4000

  mongodb:
    image: mongo:latest  # Use the latest MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017"

networks:
  mern:  # Define the 'mern' network explicitly
    driver: bridge
